### ISSUE TITLE
jupyterhubの調査

### ISSUE THREAD

**Issue by lptython** [slsfcteam/kaggle-slsfc#1]
- [x] jupyterhub の調査。今の環境に適したjupyterの環境の構築方法
- [x] 構築する(ほどほどにセキュアな感じで)

**Comment by raven38** [comment]
署名証明書必要ですよね

**Comment by lptython** [comment]
@raven38 必要だと思う。そこら辺も含めて調査でw

**Comment by habakan** [comment]
http://qiita.com/cvusk/items/afa46c35d8d5f0d930ed
先程の構築qiitaとりあえずこれ使ってローカルで試します

**Comment by lptython** [comment]
一応マイルストーンは一週間にしておきました。

**Comment by habakan** [comment]
現状の報告です。

/opt/で
> sudo pyenv local 3.5.3/envs/sealion

> jupyterhub --generate-config

/opt/jupyterhub_config.py生成
各ユーザーの~/notebookディレクトリ内のipynbを使えるようにして，
adminはsluserに設定

> sudo apt install npm
> sudo npm install -g configurable-http-proxy

http-proxyをインストール

> jupyterhub --no-ssl

で実行したが
[I 2017-05-08 11:33:36.018 JupyterHub app:1176] Starting proxy @ http://*:8000/
/usr/bin/env: ‘node’: No such file or directory
といわれる

**Comment by y4m3** [comment]
ちょっと見てみたら、
1. sluser配下ではなく、なぜか/opt配下にjupyterhub_config.pyだけが生成されてた。jupyterhub_confg.pyは
、.sqliteなどと同じディレクトリにないといけないと思われ。
2. なんとなくの感じ、sluserでjupyterhubを叩くと、権限の問題で他のユーザー、ブラウザからの閲覧が出来ないってかんじかと思われ。

あと、port管理するときは、sshの22番塞がないでね！raven！

**Comment by y4m3** [comment]
`cd /etc/jupyterhub & sudo -u jupyter /opt/.pyenv/shims/jupyterhub`
でjupyterhubは起動する。細かい、configは要設定。

ただし、ブラウザから8000番へアクセスできない問題は未だ顕在。

**Comment by raven38** [comment]
Login後、ユーザページで404が発生する問題がありましたが、

    c.Spawner.notebook_dir = '~/notebooks'

をjupyterhub_config.pyに設定して治りました。

**Comment by y4m3** [comment]
8000番問題は、ERNSの上流の問題でした。管理者sawaiにより、解決。

**Comment by lptython** [comment]
こちらのissue、進捗如何でしょう

**Comment by y4m3** [comment]
現状は、python 3.5.2で起動中(tmux上で動かしてる)。
計算自体に問題は無いと思います。

**Comment by lptython** [comment]
おっけー
全ユーザーが自分がログインしたときに立ち上げられるようになったらゴールで。
必要ならslackで チャンネル なりにメンション投げてください

**Comment by lptython** [comment]
終わったっぽいので閉じます。必要あったらまた開けてください。
